/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PayRouteImport } from './routes/pay'
import { Route as CustomerRecoverTransactionIdRouteImport } from './routes/customer.recover.$transactionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRecoverTransactionIdRoute =
  CustomerRecoverTransactionIdRouteImport.update({
    id: '/recover/$transactionId',
    path: '/recover/$transactionId',
    getParentRoute: () => CustomerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customer': typeof CustomerRouteWithChildren
  '/merchant': typeof MerchantRoute
  '/onboarding': typeof OnboardingRoute
  '/pay': typeof PayRoute
  '/customer/recover/$transactionId': typeof CustomerRecoverTransactionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customer': typeof CustomerRouteWithChildren
  '/merchant': typeof MerchantRoute
  '/onboarding': typeof OnboardingRoute
  '/pay': typeof PayRoute
  '/customer/recover/$transactionId': typeof CustomerRecoverTransactionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customer': typeof CustomerRouteWithChildren
  '/merchant': typeof MerchantRoute
  '/onboarding': typeof OnboardingRoute
  '/pay': typeof PayRoute
  '/customer/recover/$transactionId': typeof CustomerRecoverTransactionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customer'
    | '/merchant'
    | '/onboarding'
    | '/pay'
    | '/customer/recover/$transactionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customer'
    | '/merchant'
    | '/onboarding'
    | '/pay'
    | '/customer/recover/$transactionId'
  id:
    | '__root__'
    | '/'
    | '/customer'
    | '/merchant'
    | '/onboarding'
    | '/pay'
    | '/customer/recover/$transactionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomerRoute: typeof CustomerRouteWithChildren
  MerchantRoute: typeof MerchantRoute
  OnboardingRoute: typeof OnboardingRoute
  PayRoute: typeof PayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/recover/$transactionId': {
      id: '/customer/recover/$transactionId'
      path: '/recover/$transactionId'
      fullPath: '/customer/recover/$transactionId'
      preLoaderRoute: typeof CustomerRecoverTransactionIdRouteImport
      parentRoute: typeof CustomerRoute
    }
  }
}

interface CustomerRouteChildren {
  CustomerRecoverTransactionIdRoute: typeof CustomerRecoverTransactionIdRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerRecoverTransactionIdRoute: CustomerRecoverTransactionIdRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomerRoute: CustomerRouteWithChildren,
  MerchantRoute: MerchantRoute,
  OnboardingRoute: OnboardingRoute,
  PayRoute: PayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
